---
- name: Configure device credentials on Cisco Catalyst Center
  hosts: localhost
  vars_files:
    - "credentials.yml"
  connection: local
  gather_facts: no
  tasks:
    - name: application policy 
      cisco.dnac.application_policy_workflow_manager:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        dnac_log: True
        dnac_log_level: DEBUG
        config_verify: True
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: merged
        config:
          - application_policy_details:
              application_policy_name: "sample_application_policy"
              policy_status: "deployed"                                  
              site_name: "global/Chennai/LTTS/FLOOR1"       
              device_type: "wired"
              # device:              
              #   - device_ip: "204.192.6.200"
              #     vlan_id: ""
              application_queuing_profile_name: "sample_queuing_profile"      
              clause: 
                - clause_type: “BUSINESS_RELEVANCE"  
                  relevance_details:                            
                    - relevance: "BUSINESS_RELEVANT"                            
                      application_set_name: ["email", "backup-and-storage", "general-misc", "tunneling"]
                    - relevance: "BUSINESS_IRRELEVANT"                            
                      application_set_name: ["sample_application_set", "sample_application_set", "sample_application_set", "sample_application_set"]
                    - relevance: "DEFAULT"                            
                      application_set_name: ["sample_application_set", "sample_application_set", "sample_application_set", "sample_application_set"]