---
- name: Configure device credentials on Cisco DNA Center
  hosts: dnac_servers
  vars_files:
    - "credentials.yml"
  connection: local
  gather_facts: no
  tasks:
    - name: Get Device info and updating user details
      cisco.dnac.user_workflow_manager:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        dnac_log: True
        dnac_log_level: DEBUG
        config_verify: True
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: merged
        config:
          - first_name: "ajith"
            last_name: "andrew"
            email: "ajith.andrew@example.com"
            password: "Ajith@123"
            username: "ajithandrewj"
            role_list: ["OBSERVER-ROLE","SUPER-ADMIN-ROLE"]

