---
- name: Configure device credentials on Cisco Catalyst Center
  hosts: localhost
  connection: local
  gather_facts: false  # This space must be "no". It was set to false due to formatting errors.but the correct value is "no".
  vars_files:
    - "credentials.yml"
  tasks:
    - name: Provision a wired device to a site
      cisco.dnac.wireless_design_workflow_manager:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        config_verify: true
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: merged
        config:
          - feature_template_config:
              - dot11ax_configuration:
                  - design_name: "dot11ax_24ghz_design"
                    feature_attributes:
                      radio_band: "2_4GHZ"
                      bss_color: true
                      target_waketime_broadcast: false
                      non_srg_obss_pd_max_threshold: -78
                      target_wake_up_time_11ax: true
                      obss_pd: true
                    unlocked_attributes:
                      - "radio_band"
                      - "bss_color"
